const Lang = {
    tools: {
        zero_denominator_error: "denominator can not be 0",
        no_number_input: "please input a number",
        range: "range",
        step: "step"
    },
    jointdensity: {
        label: "Joint Probability Density",
        range: "Range",
        coefficient: "Coefficient",
        slice: "Slice",
        realtime: "realtime slice",
        graph: "Graph Properties",
        precise: "precise",
        color_of_maxval: "color of max",
        color_of_minval: "color of min",
        is_perspective: "perspective",
        graph_2D_title: ", area is",
    },
    normal: {
        label: "Normal-Histogram of sample means",
        section_distribution_name: "Distribution",
        avg: "the average of sample mean",
        std: "standard deviation",
        section_experiment_name: "Experiment",
        sample_num: "sample size",
        try_times: "repeat times",
        curve_props: "Line Chart",
        curve_color: "line color",
        curve_range: "range",
        curve_precise: "precise",
        curve_graph_name: "distribution of population",
        curve_2_graph_name: "distribution of x̄",
        bars_props: "Histogram",
        bars_color: "color of bars",
        bars_gap: "gap between bars",
        bars_graph_name: "Histogram of sample means",
        experiment: "experiment",
        variance: "the average of sample variance",
        start_btn_text: "Run",
        no_result_tips: "there is no result",
    },
    normalCI: {
        label: "Normal-Confidence interval for the mean",
        section_distribution_name: "Distribution",
        avg: "sample mean",
        std: "standard deviation",
        section_experiment_name: "Experiment",
        sample_num: "sample size",
        try_times: "repeat times",
        confidence_interval_config: "Confidence",
        confidence_level: "Confidence level（1 - α）",
        confidence_interval_formula: "confidence interval of mean",
        display_props: "Display settings",
        formula_size: "formula size",
        interval_safe_color: "contains the true value",
        interval_danger_color: "misses the true value",
        interval_height: "height of interval",
        interval_scale: "width of interval",
        interval_gap: "gap between intervals",
        start_btn_text: "Run",
        no_result_tips: "there is no result",
        view_table: "open the t-distribution table",
        table_name: "t-distribution table",
        safe_frequency: "frequency of true value contained: ",
        safe_description: "number of true value contained: ",
        unsafe_description: "number of true value missed: ",
    },
    normalSL: {
        label: "Hypothesis Testing",
        section_distribution_name: "Distribution",
        null_hypotheses: "null hypothesis μ",
        alternative_hypotheses: "alternative hypotheses",
        section_experiment_name: "Experiment",
        sample_num: "sample size",
        try_times: "repeat times",
        significant_level: "significant level",
        deny_area: "deny area:",
        formula_description: "When the two-sided test null hypothesis holds",
        display_props: "settings",
        formula_size: "formula size",
        view_table: "open the t-distribution table",
        table_name: "t-distribution table",
        result_btn_text: "Run",
        result1_title: "When the null hypothesis holds",
        result1_accept: "correctly do not reject the null hypothesis",
        result1_deny: "falsely reject the null hypothesis",
        result1_frequency: "Frequency of making Type 1 mistakes",
        result1_tips_1: "The generated random numbers obey the mean of",
        result1_tips_2: "the variance is",
        result1_tips_3: "normal distribution",
        result2_title: "when the null hypothesis does not hold",
        result2_accept: "falsely not rejecting the null hypothesis",
        result2_deny: "correctly reject the null hypothesis",
        result2_frequency: "Frequency of making Type 2 errors",
        result2_tips_1: "The generated random numbers obey the mean of",
        result2_tips_2: "the variance is",
        result2_tips_3: "normal distribution",
    },
    zeroone: {
        label: "0 1-Histogram of sample means",
        section_distribution_name: "0 1-Distribution",
        p: 'p',
        avg: "the average of sample mean",
        std: "standard deviation",
        section_experiment_name: "Experiment",
        sample_num: "sample size",
        try_times: "repeat times",
        distribution_props: "Distribution",
        distribution_graph_name: "Distribution of population",
        bars_props: "Histogram",
        bars_color: "color of bars",
        bars_gap: "gap of bars",
        bars_graph_name: "Histogram of sample means",
        experiment: "Experiment",
        variance: "the average of sample variance",
        start_btn_text: "Run",
        no_result_tips: "there is no result",
    },
    zerooneCI: {
        label: "0 1-Confidence interval for the p",
        section_distribution_name: "0 1 Distribution",
        p: 'p',
        section_experiment_name: "Experiment",
        sample_num: "sample size",
        try_times: "repeat times",
        confidence_interval_config: "Confidence",
        confidence_level: "Confidence level（1 - α）",
        confidence_interval_formula: "confidence interval of mean",
        display_props: "Display settings",
        formula_size: "formula size",
        interval_safe_color: "contains the true value",
        interval_danger_color: "misses the true value",
        interval_height: "height of interval",
        interval_scale: "width of interval",
        interval_gap: "gap between intervals",
        start_btn_text: "Run",
        no_result_tips: "there is no result",
        view_table: "open standard normal distribution table",
        table_name: "standard normal distribution table",
        safe_frequency: "frequency of true value contained: ",
        safe_description: "number of true value contained: ",
        unsafe_description: "number of true value missed: ",
    },
    zerooneSL: {
        label: "Hypothesis Testing",
        section_distribution_name: "Distribution",
        null_hypotheses: "null hypothesis p",
        alternative_hypotheses: "alternative hypotheses",
        section_experiment_name: "Experiment",
        sample_num: "sample size",
        try_times: "repeat times",
        significant_level: "significant level",
        deny_area: "deny area:",
        formula_description: "When the two-sided test null hypothesis holds",
        display_props: "settings",
        formula_size: "formula size",
        view_table: "open the standard normal distribution table",
        table_name: "standard normal distribution table",
        result_btn_text: "Run",
        result1_title: "When the null hypothesis holds",
        result1_accept: "correctly do not reject the null hypothesis",
        result1_deny: "falsely reject the null hypothesis",
        result1_frequency: "Frequency of making Type 1 mistakes",
        result1_tips_1: "The generated random numbers obey the 0-1 distribution with a probability of ",
        result1_tips_2: "",
        result1_tips_3: "",
        result2_title: "when the null hypothesis does not hold",
        result2_accept: "falsely not rejecting the null hypothesis",
        result2_deny: "correctly reject the null hypothesis",
        result2_frequency: "Frequency of making Type 2 errors",
        result2_tips_1: "The generated random numbers obey the 0-1 distribution with a probability of ",
        result2_tips_2: "",
        result2_tips_3: "",
    },
}