const Lang = {
    tools: {
        zero_denominator_error: "denominator can not be 0",
        no_number_input: "please input a number",
        range: "range",
        step: "step"
    },
    jointdensity: {
        label: "Joint Probability Density",
        range: "Range",
        coefficient: "Coefficient",
        slice: "Slice",
        realtime: "realtime slice",
        graph: "Graph Properties",
        precise: "precise",
        color_of_maxval: "color of max",
        color_of_minval: "color of min",
        is_perspective: "perspective",
        graph_2D_title: ", area is",
    },
    normal: {
        label: "Normal-Histogram of sample means",
        section_distribution_name: "Distribution",
        avg: "sample mean",
        std: "standard deviation",
        section_experiment_name: "Experiment",
        sample_num: "sample size",
        try_times: "repeat times",
        curve_props: "Line Chart",
        curve_color: "line color",
        curve_range: "range",
        curve_precise: "precise",
        curve_graph_name: "distribution",
        curve_2_graph_name: "distribution of x̄",
        bars_props: "Histogram",
        bars_color: "color of bars",
        bars_gap: "gap between bars",
        bars_graph_name: "Histogram of sample means",
        experiment: "experiment",
        variance: "sample variance",
        start_btn_text: "Run",
        no_result_tips: "there is no result",
    },
    normalCI: {
        label: "Normal-Confidence interval for the mean",
        section_distribution_name: "Distribution",
        avg: "sample mean",
        std: "standard deviation",
        section_experiment_name: "Experiment",
        sample_num: "sample size",
        try_times: "repeat times",
        confidence_interval_config: "Confidence",
        confidence_level: "Confidence level（1 - α）",
        confidence_interval_formula: "confidence interval of sample mean",
        display_props: "Display settings",
        formula_size: "formula size",
        interval_safe_color: "contains the true value",
        interval_danger_color: "misses the true value",
        interval_height: "height of interval",
        interval_scale: "width of interval",
        interval_gap: "gap between intervals",
        start_btn_text: "Run",
        no_result_tips: "there is no result",
        view_table: "open the t-distribution table",
        table_name: "t-distribution table",
        safe_frequency: "frequency of true value contained: ",
        safe_description: "number of true value contained: ",
        unsafe_description: "number of true value missed: ",
    },
    normalSL: {
        label: "Hypothesis Testing",
        section_distribution_name: "Distribution",
        null_hypotheses: "原假设 μ",
        alternative_hypotheses: "备择假设",
        section_experiment_name: "实验设置",
        sample_num: "样本容量",
        try_times: "重复次数",
        significant_level: "显著性水平",
        deny_area: "拒绝域：",
        formula_description: "双边检验原假设成立时：",
        display_props: "展示设置",
        formula_size: "公式大小",
        view_table: "查看标准正态分布表",
        table_name: "标准正态分布表",
        result_btn_text: "开始实验",
        result1_title: "当原假设成立时",
        result1_accept: "正确地不拒绝原假设",
        result1_deny: "错误地拒绝原假设",
        result1_frequency: "犯错第一类错误的频率：",
        result1_tips_1: "产生的随机数服从均值为",
        result1_tips_2: "方差为",
        result1_tips_3: "的正态分布",
        result2_title: "当原假设不成立时",
        result2_accept: "错误地不拒绝原假设",
        result2_deny: "正确地拒绝原假设",
        result2_frequency: "犯错第二类错误的频率：",
        result2_tips_1: "产生的随机数服从均值为",
        result2_tips_2: "方差为",
        result2_tips_3: "的正态分布",
    },
    zeroone: {
        label: "0 1-Histogram of sample means",
        section_distribution_name: "0 1-Distribution",
        p: 'p',
        avg: "sample mean",
        std: "standard deviation",
        section_experiment_name: "Experiment",
        sample_num: "sample size",
        try_times: "repeat times",
        distribution_props: "Distribution",
        distribution_graph_name: "Distribution",
        bars_props: "Histogram",
        bars_color: "color of bars",
        bars_graph_name: "Histogram of sample means",
        experiment: "Experiment",
        variance: "sample variance",
        start_btn_text: "Run",
        no_result_tips: "there is no result",
    },
    zerooneCI: {
        label: "0 1-Confidence interval for the p",
        section_distribution_name: "0 1 Distribution",
        p: 'p',
        section_experiment_name: "Experiment",
        sample_num: "sample size",
        try_times: "repeat times",
        confidence_interval_config: "Confidence",
        confidence_level: "Confidence level（1 - α）",
        confidence_interval_formula: "confidence interval of sample mean",
        display_props: "Display settings",
        formula_size: "formula size",
        interval_safe_color: "contains the true value",
        interval_danger_color: "misses the true value",
        interval_height: "height of interval",
        interval_scale: "width of interval",
        interval_gap: "gap between intervals",
        start_btn_text: "Run",
        no_result_tips: "there is no result",
        view_table: "open standard normal distribution table",
        table_name: "standard normal distribution table",
        safe_frequency: "frequency of true value contained: ",
        safe_description: "number of true value contained: ",
        unsafe_description: "number of true value missed: ",
    },
}