const Lang = {
    tools: {
        zero_denominator_error: "分母不能为零",
        no_number_input: "请输入正确的数字",
    },
    jointdensity: {
        label: "联合概率密度",
        range: "取值范围",
        coefficient: "系数",
        slice: "切面",
        realtime: "实时切面",
        graph: "图像属性",
        precise: "绘图误差",
        color_of_maxval: "最大值颜色",
        color_of_minval: "最小值颜色",
        is_perspective: "透视视角",
        graph_2D_title: "的切面，面积为",
    },
    normal: {
        label: "总体正态分布",
        section_distribution_name: "总体正态分布",
        avg: "均值",
        std: "标准差",
        section_experiment_name: "实验设置",
        sample_num: "样本容量",
        try_times: "重复次数",
        curve_props: "分布图属性",
        curve_color: "线条颜色",
        curve_precise: "绘图误差",
        curve_graph_name: "总体分布",
        bars_props: "直方图属性",
        bars_color: "填充颜色",
        bars_gap: "列间距",
        bars_graph_name: "样本均值的直方图",
        experiment: "实验",
        variance: "方差",
        start_btn_text: "开始实验并记录结果",
        no_result_tips: "没有实验结果展示",
    },
    normalCI: {
        label: "总体正态分布-置信区间",
        section_distribution_name: "总体正态分布",
        avg: "均值",
        std: "标准差",
        section_experiment_name: "实验设置",
        sample_num: "样本容量",
        try_times: "重复次数",
        confidence_interval_config: "置信区间设置",
        confidence_level: "置信水平（1 - α）",
        confidence_interval_formula: "均值的置信区间公式",
        display_props: "展示设置",
        formula_size: "公式大小",
        interval_safe_color: "包含真值的区间颜色",
        interval_danger_color: "不包含真值的区间颜色",
        interval_height: "区间高度",
        interval_gap: "区间间距",
        start_btn_text: "开始实验并记录结果",
        no_result_tips: "没有实验结果展示",
        view_table: "查看标准正态分布表",
        table_name: "标准正态分布表",
        safe_description: "包含真值的观测个数：",
        unsafe_description: "不包含真值的观测个数：",
    },
    zeroone: {
        label: "0 1 分布",
        section_distribution_name: "总体 0 1 分布",
        p: 'p',
        avg: "均值",
        std: "标准差",
        section_experiment_name: "实验设置",
        sample_num: "样本容量",
        try_times: "重复次数",
        distribution_props: "分布图属性",
        distribution_graph_name: "总体分布",
        bars_props: "直方图属性",
        bars_color: "填充颜色",
        bars_graph_name: "样本均值的直方图",
        experiment: "实验",
        variance: "方差",
        start_btn_text: "开始实验并记录结果",
        no_result_tips: "没有实验结果展示",
    }
}