const Lang = {
    tools: {
        zero_denominator_error: "分母不能为零",
        no_number_input: "请输入正确的数字",
        range: "取值范围",
        step: "步长",
    },
    jointdensity: {
        label: "联合概率密度",
        range: "取值范围",
        coefficient: "系数",
        slice: "切面",
        realtime: "实时切面",
        graph: "图像属性",
        precise: "绘图误差",
        color_of_maxval: "最大值颜色",
        color_of_minval: "最小值颜色",
        is_perspective: "透视视角",
        graph_2D_title: "的切面，面积为",
    },
    normal: {
        label: "总体正态分布-样本均值直方图",
        section_distribution_name: "总体正态分布",
        avg: "样本均值的均值",
        std: "标准差",
        section_experiment_name: "实验设置",
        sample_num: "样本容量",
        try_times: "重复次数",
        curve_props: "分布图属性",
        curve_color: "线条颜色",
        curve_range: "的取值范围",
        curve_precise: "绘图误差",
        curve_graph_name: "总体分布",
        curve_2_graph_name: "x̄ 的分布",
        bars_props: "直方图属性",
        bars_color: "填充颜色",
        bars_gap: "列间距",
        bars_graph_name: "样本均值的直方图",
        experiment: "实验",
        variance: "样本均值的方差",
        start_btn_text: "开始实验并记录结果",
        no_result_tips: "没有实验结果展示",
    },
    normalCI: {
        label: "总体正态分布-均值的置信区间",
        section_distribution_name: "总体正态分布",
        avg: "均值",
        std: "标准差",
        section_experiment_name: "实验设置",
        sample_num: "样本容量",
        try_times: "重复次数",
        confidence_interval_config: "置信区间设置",
        confidence_level: "置信水平（1 - α）",
        confidence_interval_formula: "均值的置信区间公式",
        display_props: "展示设置",
        formula_size: "公式大小",
        interval_safe_color: "包含真值的区间颜色",
        interval_danger_color: "不包含真值的区间颜色",
        interval_height: "区间高度",
        interval_scale: "区间宽度",
        interval_gap: "区间间距",
        start_btn_text: "开始实验并记录结果",
        no_result_tips: "没有实验结果展示",
        view_table: "打开 t 分布计算器",
        table_name: "t 分布计算器",
        safe_frequency: "包含真值的观测频率：",
        safe_description: "包含真值的观测个数：",
        unsafe_description: "不包含真值的观测个数：",
    },
    normalSL: {
        label: "总体正态分布-假设检验",
        section_distribution_name: "总体正态分布",
        null_hypotheses: "原假设 μ",
        alternative_hypotheses: "备择假设",
        section_experiment_name: "实验设置",
        sample_num: "样本容量",
        try_times: "重复次数",
        significant_level: "显著性水平",
        deny_area: "拒绝域：",
        formula_description: "双边检验原假设成立时：",
        display_props: "展示设置",
        formula_size: "公式大小",
        view_table: "查看标准正态分布表",
        table_name: "标准正态分布表",
        result_btn_text: "开始实验",
        result1_title: "当原假设成立时",
        result1_accept: "正确地不拒绝原假设",
        result1_deny: "错误地拒绝原假设",
        result1_frequency: "犯错第一类错误的频率：",
        result1_tips_1: "产生的随机数服从均值为",
        result1_tips_2: "方差为",
        result1_tips_3: "的正态分布",
        result2_title: "当原假设不成立时",
        result2_accept: "错误地不拒绝原假设",
        result2_deny: "正确地拒绝原假设",
        result2_frequency: "犯错第二类错误的频率：",
        result2_tips_1: "产生的随机数服从均值为",
        result2_tips_2: "方差为",
        result2_tips_3: "的正态分布",
    },
    zeroone: {
        label: "0 1 分布-样本均值直方图",
        section_distribution_name: "总体 0 1 分布",
        p: 'p',
        avg: "样本均值的均值",
        std: "标准差",
        section_experiment_name: "实验设置",
        sample_num: "样本容量",
        try_times: "重复次数",
        distribution_props: "分布图属性",
        distribution_graph_name: "总体分布",
        bars_props: "直方图属性",
        bars_color: "填充颜色",
        bars_gap: "间距",
        bars_graph_name: "样本均值的直方图",
        experiment: "实验",
        variance: "样本均值的方差",
        start_btn_text: "开始实验并记录结果",
        no_result_tips: "没有实验结果展示",
    },
    zerooneCI: {
        label: "0 1 分布-p 的置信区间",
        section_distribution_name: "总体 0 1 分布",
        p: 'p',
        section_experiment_name: "实验设置",
        sample_num: "样本容量",
        try_times: "重复次数",
        confidence_interval_config: "置信区间设置",
        confidence_level: "置信水平（1 - α）",
        confidence_interval_formula: "均值的置信区间公式",
        display_props: "展示设置",
        formula_size: "公式大小",
        interval_safe_color: "包含真值的区间颜色",
        interval_danger_color: "不包含真值的区间颜色",
        interval_height: "区间高度",
        interval_scale: "区间宽度",
        interval_gap: "区间间距",
        start_btn_text: "开始实验并记录结果",
        no_result_tips: "没有实验结果展示",
        view_table: "查看标准正态分布表",
        table_name: "标准正态分布表",
        safe_frequency: "包含真值的观测频率：",
        safe_description: "包含真值的观测个数：",
        unsafe_description: "不包含真值的观测个数：",
    },
}